add events and modules to core client
backtrace-labs/backtrace-javascript pull request #146
Opened 2023-09-19 12:22 UTC by perf2711

This diff aims to reduce coupling between some modules and the core client. The main reason is to make the client less dependent on the external modules, which the client can function perfectly fine without.

* `Events` class was added, which is an event emitter similar to Node's `EventEmitter`, but not node-dependent,
* module map was added,
* database, metrics, breadcrumbs were moved to modules,
* database and breadcrumbs are no longer called by the client directly, but rather through Events.

Also moved `initialize` out of constructor and to the builders. The reason for that is to defer initialization of modules to after the class has been constructed.

2023-09-19 13:05 UTC, perf2711 commented on packages/sdk-core/src/BacktraceCoreClient.ts
> +export type ReportEvents = {
Done

2023-09-19 13:14 UTC, konraddysput commented on packages/sdk-core/src/modules/database/BacktraceDatabase.ts
> +            const record = this._databaseRecordContext.find((record) => record.data === data);
with the current implementation there is a chance you will remove the wrong report. Maybe we should add id to the report and re-use it in the backtracedata instead?

2023-09-19 14:06 UTC, perf2711 commented on packages/sdk-core/src/modules/database/BacktraceDatabase.ts
> +            const record = this._databaseRecordContext.find((record) => record.data === data);
how? this is referential comparison, there's no way this will be different

2023-09-19 14:28 UTC, perf2711 commented on packages/sdk-core/src/modules/database/BacktraceDatabase.ts
> +            const record = this._databaseRecordContext.find((record) => record.data === data);
still, the report may be a different object that we expect. Maybe it's a good idea after all to add an ID to the report.

2023-09-19 14:49 UTC, perf2711 commented on packages/sdk-core/src/BacktraceCoreClient.ts
> +        return this;
done

2023-09-19 14:56 UTC, perf2711 commented on packages/sdk-core/src/modules/database/BacktraceDatabase.ts
> +            const record = this._databaseRecordContext.find((record) => record.data === data);
I've changed it to find by UUID. It's generated uniquely for each data object.

2023-09-19 16:32 UTC, perf2711 commented on packages/sdk-core/src/modules/database/BacktraceDatabase.ts
> +            const record = this._databaseRecordContext.find((record) => record.data === data);
same errors? but isn't BacktraceData generated uniquely for each send?

2023-09-19 17:36 UTC, konraddysput requested changes

2023-09-19 17:36 UTC, konraddysput commented on packages/sdk-core/src/BacktraceCoreClient.ts
> +        for (const module of this._modules.values()) {
we talked about this via slack but what is the advantage of this? Actually via map we're hiding what modules we're initializing. The previous version allowed us to clearly says what starts and when. Now we need to check when we're adding it. Backtrace Client isn't less dependent than it was earlier but instead we're hiding something behind the implementation detail.


Why this is better solution if the number of modules previously initialized was seriously small?

2023-09-19 17:36 UTC, konraddysput commented on packages/sdk-core/src/modules/database/BacktraceDatabase.ts
> +    public bind(client: BacktraceCoreClient): void {
if this is public api - can we add a summary description?

2023-09-19 17:36 UTC, konraddysput commented on packages/sdk-core/src/BacktraceCoreClient.ts
> +    public readonly reportEvents: Events<ReportEvents>;
shouldn't it be protected? There is no need to leave it public

2023-09-21 13:00 UTC, konraddysput approved these changes

2023-09-22 12:27 UTC, konraddysput approved these changes

2023-09-27 08:03 UTC, merged