electron example: add an example for using Electron SDK
backtrace-labs/backtrace-javascript pull request #177
Opened 2023-10-16 12:33 UTC by perf2711

This PR adds an example showcasing features of Backtrace in Electron, and how to initialize it in an Electron app.

Jira task: BT-709

2023-10-16 14:26 UTC, konraddysput requested changes

2023-10-16 14:26 UTC, konraddysput commented on examples/sdk/electron/assets/index.html
> +                    <div class="button-container center">
Can we add crash?

2023-10-16 14:26 UTC, konraddysput commented on examples/sdk/electron/src/main/consts.ts
> +    'https://salex.in.backtrace.io:6098/post?format=json&token=81ebe51f9caa641c2013b15b59f704a853a70e542ce279a90bf1526853d8ff0a';
salex submission url

2023-10-16 14:52 UTC, perf2711 commented on examples/sdk/electron/assets/index.html
> +                    <div class="button-container center">
94-96:
```
<div class="action-button crash-app" data-target="main">
                        <a class="text" target="_blank">Crash application</a>
                    </div>
```

2023-10-19 15:59 UTC, konraddysput approved these changes

2023-10-19 16:04 UTC, merged