scripts: add scripts for making releases
backtrace-labs/backtrace-javascript pull request #182
Opened 2023-10-17 12:29 UTC by perf2711

This PR adds two scripts:
* gitRelease.ts - for a package, increments version, commits the version update to <package>/<version>
* release.ts - for a package, releases current version and creates a tag on HEAD or provided commit hash

Scripts have a rudimentary transaction capability - if something fails on the way, the script will try to undo all stuff it did.

sdk-core/0.0.7 was released using these scripts.

2023-10-18 09:15 UTC, konraddysput requested changes
Overall all changes look great, however, can we add a quick readme with information how to use those tools?

2023-10-19 11:16 UTC, perf2711 commented on scripts/common/output.ts
> +    process.stderr.write(message + '\n');
It is by design, so you can use the output for chaining to other stuff.

2023-10-19 11:16 UTC, perf2711 commented on scripts/common/packageJson.ts
> +        throw error;
Done.

2023-10-19 11:16 UTC, perf2711 commented on scripts/gitRelease.ts
> +    if (!packageJsonPath) {
Done.

2023-10-19 11:43 UTC, konraddysput approved these changes

2023-10-19 15:45 UTC, konraddysput commented on scripts/common/output.ts
> +    process.stderr.write(message + '\n');
yeah but it has to be stderr? You cannot use stdout?

2023-10-31 09:48 UTC, merged